### ISSUE TITLE
Installing GIT first

### ISSUE THREAD

**Issue by Rickardo987** [ThatNerdyPikachu/LaunchpadNX#2]
For some people who aren't aware of how devkit works, it might be good to tell them to install GIT first and then devkit. This is because devkit requires GIT to install.

**Comment by Rickardo987** [comment]
oh and devkit needs admin privileges.

**Comment by ThatNerdyPikachu** [comment]
devkit asks for admin perms

**Comment by Rickardo987** [comment]
oh, didnt for me sorry
